services:
  app:
    container_name: vesper_app
    build: .
    ports:
      - "80:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vesper-net

  db:
    container_name: vesper_db
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=vesper_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=America/Argentina/Buenos_Aires
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vesper-net

volumes:
  db_data:

networks:
  vesper-net:
    driver: bridge