services:
  app:
    container_name: vesper_app
    build: .
    ports:
      - "80:8080" # Accederás a tu app en http://localhost:80 (sin puerto)
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vesper-net

  db:
    container_name: vesper_db
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" # Para entrar con Workbench usa localhost:3307
    environment:
      # Debe coincidir con el nombre en la URL del .env
      - MYSQL_DATABASE=vesper_db 
      # Crea este usuario específico (traido del .env)
      - MYSQL_USER=${DB_USERNAME} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
      # Contraseña para el superusuario root
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=America/Argentina/Buenos_Aires
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vesper-net

volumes:
  db_data:

networks:
  vesper-net:
    driver: bridge