spring.application.name=Vesper

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# = AUTH0 CONFIG
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://vesperarg.us.auth0.com/
auth0.audience=https://verper/api

# ===============================
# = CORS
# ===============================
web.cors.allowed-origins=http://127.0.0.1:5500

# ===============================
# = DATA SOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/db_vesper?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = JWT
# ===============================
jwt.secret=Yz9$Qw4!pL7v@2tGmC8rXfJ^kB6hN%aS0dUoE*R3
jwt.expiration=604800000  # 7 días

# ===============================
# = SERVER
# ===============================
server.port=8080

# ===============================
# = EMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=scriptgangecommerce@gmail.com
spring.mail.password=zuef oddu wyyi guun
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# CLOUDINARY CONFIG
# ===============================
cloudinary.url=cloudinary://611432554646842:VWJLT1Djw9_Aw6mJkbC_lU0FvPM@do0ywdrkv

# ===============================
# SPRING UPLOAD CONFIG
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# MERCADO PAGO
# ===============================
mercadopago.access-token=APP_USR-8730117218160065-101616-807cf31233db59dafd21be8f1cf56840-2930281505
mercadopago.base.url=https://seminocturnal-willena-unbeseeching.ngrok-free.dev
mercadopago.webhook.secret=23c8efee76f639be4f7d040672af88b62897acb4403f8186ce78cd13a4a98624
mercadopago.public-key=APP_USR-011fa53a-4a64-4af4-be14-7fb28f6e5200
